// tb/sim_main.cpp
// Verilator C++ testbench for apu_vga_timing
// Compile with: verilator --cc --exe --build -Wall \
//               rtl/apu_pkg.sv rtl/apu_vga_timing.sv tb/sim_main.cpp

#include "Vapu_vga_timing.h"   // Auto-generated by Verilator (matches module name)
#include "verilated.h"
#include <cstdio>
#include <cstdint>

int main(int argc, char **argv) {
    Verilated::commandArgs(argc, argv);
    
    // Instantiate the DUT (Design Under Test)
    auto *tb = new Vapu_vga_timing;
    
    // === PHASE 1: Reset Sequence ===
    // TODO: Initialize clk_pix_i to 0
    int clk_pix_i = 0;
    // TODO: Assert reset (rst_n_i = 0, remember it's ACTIVE LOW)
    tb->rst_n_i = 0;
    // TODO: Toggle clock 20 times (10 full cycles) while holding reset
    //       Each cycle: set clk=1, eval(), set clk=0, eval()
    for (int i = 0; i < 20; i++) {
        clk_pix_i = 1;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
        
        clk_pix_i = 0;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
    }
    // TODO: Release reset (rst_n_i = 1)
    tb->rst_n_i = 1;
    
    // === PHASE 2: Measurement Variables ===
    // TODO: Declare these variables:
       uint64_t de_count = 0;           // Total DE cycles across all frames
       uint64_t hsync_width = 0;        // Current HSync low-pulse counter
       uint64_t vsync_lines = 0;        // Current VSync line counter  
       uint64_t frame_cycles = 0;       // Cycles since last SOF
       uint64_t sof_count = 0;          // Number of SOF pulses seen
       bool prev_sof = false;           // Previous cycle's sof_o value
       bool prev_hsync = true;          // Previous cycle's hsync_o value
       bool prev_vsync = true;          // Previous cycle's vsync_o value
       FILE *ppm_fp = nullptr;          // PPM output file handle
    
    // === PHASE 3: Open PPM File ===
    // TODO: Open "sim/frame.ppm" for binary write ("wb")
    ppm_fp = fopen("sim/frame.ppm", "wb");
    // TODO: Write PPM header: "P6\n640 480\n255\n"
    //       Use fprintf(ppm_fp, "P6\n640 480\n255\n");
    fprintf(ppm_fp, "P6\n640 480\n255\n");
    
    // === PHASE 4: Main Simulation Loop ===
    // Run for 2 full frames = 2 * H_TOTAL * V_TOTAL pixel clocks
    // Use apu_pkg constants: 800 * 525 * 2 = 840000 cycles
    const uint64_t TOTAL_CYCLES = 840000;
    
    for (uint64_t cycle = 0; cycle < TOTAL_CYCLES; cycle++) {
        
        // --- Rising Clock Edge ---
        // TODO: Set clk_pix_i = 1
        clk_pix_i = 1;
        tb->clk_pix_i = clk_pix_i;
        // TODO: Call tb->eval()
        tb->eval();
        
        // --- Sample Outputs (after eval on rising edge) ---
        // TODO: Read tb->de_o, tb->hsync_o, tb->vsync_o, tb->sof_o
        //       tb->x_o, tb->y_o into local variables
        bool de_o = tb->de_o;
        bool hsync_o = tb->hsync_o;
        bool vsync_o = tb->vsync_o;
        bool sof_o = tb->sof_o;
        uint16_t x_o = tb->x_o;
        uint16_t y_o = tb->y_o;

        // --- DE Counting ---
        // TODO: If de_o is high, increment de_count
        if (de_o) {
            de_count++;
        }
        // TODO: If de_o is high, write x→R, y→G, 0x80→B to ppm_fp
        //       R = (x_o >> 2) & 0xFF
        //       G = (y_o >> 1) & 0xFF

        if (de_o && sof_count <= 1) {  // Only first frame, only during active video
            uint8_t r = (x_o >> 2) & 0xFF;
            uint8_t g = (y_o >> 1) & 0xFF;
            uint8_t b = 0x80;
            fputc(r, ppm_fp);
            fputc(g, ppm_fp);
            fputc(b, ppm_fp);
        }
        
        // --- SOF Detection (rising edge) ---
        // TODO: If sof_o == 1 AND prev_sof == 0:
        //         Increment sof_count
        //         Print frame period: printf("Frame %lu: %lu px clocks\n", ...)
        //         Reset frame_cycles to 0

        if (sof_o && !prev_sof) {
            sof_count++;
            printf("Frame %lu: %lu px clocks\n", sof_count, frame_cycles);
            frame_cycles = 0;
            
            // Count VSync lines here while prev_sof still holds previous value
            if (!vsync_o) {
                vsync_lines++;
            }
        }
        prev_sof = sof_o;
        
        // --- HSync Pulse Width Measurement ---
        // TODO: If hsync_o == 0, increment hsync_width
        if (!hsync_o) {
            hsync_width++;
        }
        // TODO: If hsync_o == 1 AND prev_hsync == 0:
        //         Print measured width: printf("HSync pulse: %lu px\n", ...)
        //         Reset hsync_width to 0
        if (hsync_o && !prev_hsync) {
            printf("HSync pulse: %lu px\n", hsync_width);
            hsync_width = 0;
        }
        // TODO: Update prev_hsync = current hsync_o
        prev_hsync = hsync_o;
        // --- VSync Line Count Measurement ---
        // TODO: On each SOF (same condition as above), if vsync_o == 0:
        //         Increment vsync_lines
        // TODO: If vsync_o == 1 AND prev_vsync == 0:
        //         Print measured lines: printf("VSync lines: %lu\n", ...)
        //         Reset vsync_lines to 0
        if (vsync_o && !prev_vsync) {
            printf("VSync lines: %lu\n", vsync_lines);
            vsync_lines = 0;
        }
        // TODO: Update prev_vsync = current vsync_o
        prev_vsync = vsync_o;
        
        // --- Frame Cycle Counter ---
        // TODO: Increment frame_cycles unconditionally
        frame_cycles++;
        
        // --- Falling Clock Edge ---
        clk_pix_i = 0;
        tb->clk_pix_i = clk_pix_i;   // ← add this line
        tb->eval();
    }
    
    // === PHASE 5: Final Assertions ===
    // TODO: Close ppm_fp
    fclose(ppm_fp);
    // TODO: Print DE count with expected value (307200 per frame × 2 = 614400)
    printf("Total DE cycles: %lu (expected 614400)\n", de_count);
    // TODO: Print PASS/FAIL for each metric
    if (de_count == 614400) {
        printf("DE count: PASS\n");
    } else {
        printf("DE count: FAIL\n");
    }
    // TODO: Delete tb
    delete tb;
    
    return 0;
}