// tb/sim_main.cpp
// Verilator C++ testbench for apu_vga_timing
// Compile with: verilator --cc --exe --build -Wall \
//               rtl/apu_pkg.sv rtl/apu_vga_timing.sv tb/sim_main.cpp

#include "Vapu_top.h"   // Auto-generated by Verilator
#include "verilated.h"
#include <cstdio>
#include <cstdint>

int main(int argc, char **argv) {
    Verilated::commandArgs(argc, argv);
    
    // Instantiate the DUT (Design Under Test)
    auto *tb = new Vapu_top;
    
    // === PHASE 1: Reset Sequence ===
    // TODO: Initialize clk_pix_i to 0
    int clk_pix_i = 0;
    // TODO: Assert reset (rst_n_i = 0, remember it's ACTIVE LOW)
    tb->rst_n_i = 0;
    // TODO: Toggle clock 20 times (10 full cycles) while holding reset
    //       Each cycle: set clk=1, eval(), set clk=0, eval()
    for (int i = 0; i < 20; i++) {
        clk_pix_i = 1;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
        
        clk_pix_i = 0;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
    }
    // TODO: Release reset (rst_n_i = 1)
    tb->rst_n_i = 1;
    
    // === PHASE 2: Measurement Variables ===
    // TODO: Declare these variables:
       uint64_t de_count = 0;           // Total DE cycles across all frames
       uint64_t hsync_width = 0;        // Current HSync low-pulse counter
       uint64_t vsync_lines = 0;        // Current VSync line counter  
       uint64_t frame_cycles = 0;       // Cycles since last SOF
       uint64_t sof_count = 0;          // Number of SOF pulses seen
       bool prev_sof = false;           // Previous cycle's sof_o value
       bool prev_hsync = true;          // Previous cycle's hsync_o value
       bool prev_vsync = true;          // Previous cycle's vsync_o value
       FILE *ppm_fp = nullptr;          // PPM output file handle
    
    // === PHASE 3: Open PPM File ===
    ppm_fp = fopen("sim/frame.ppm", "wb");
    fprintf(ppm_fp, "P6\n640 480\n255\n");
    
    // === PHASE 4: Main Simulation Loop ===
    // Run for 2 full frames = 2 * H_TOTAL * V_TOTAL pixel clocks
    // Use apu_pkg constants: 800 * 525 * 2 = 840000 cycles
    const uint64_t TOTAL_CYCLES = 840000;
    
    for (uint64_t cycle = 0; cycle < TOTAL_CYCLES; cycle++) {
        
        // --- Rising Clock Edge ---
        clk_pix_i = 1;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
        
        // --- Sample Outputs (after eval on rising edge) ---

        bool de_o = tb->de_o;
        bool hsync_o = tb->hsync_o;
        bool vsync_o = tb->vsync_o;
        bool sof_o = tb->sof_o;

        // --- DE Counting ---

        if (de_o) {
            de_count++;
        }

        // --- Pixel capture: write the DUT's real RGB332 output ---
        if (de_o && sof_count <= 1) {
            uint8_t rgb = tb->rgb_o;
            uint8_t r3 = (rgb >> 5) & 0x7;   // bits [7:5]
            uint8_t g3 = (rgb >> 2) & 0x7;   // bits [4:2]
            uint8_t b2 =  rgb       & 0x3;   // bits [1:0]
            
            // Expand to 8 bits/channel via bit replication
            uint8_t r8 = (r3 << 5) | (r3 << 2) | (r3 >> 1);
            uint8_t g8 = (g3 << 5) | (g3 << 2) | (g3 >> 1);
            uint8_t b8 = (b2 << 6) | (b2 << 4) | (b2 << 2) | b2;
            
            fputc(r8, ppm_fp);
            fputc(g8, ppm_fp);
            fputc(b8, ppm_fp);
        }
        
        // --- SOF Detection (rising edge) ---

        if (sof_o && !prev_sof) {
            sof_count++;
            printf("Frame %lu: %lu px clocks\n", sof_count, frame_cycles);
            frame_cycles = 0;
            
            // Count VSync lines here while prev_sof still holds previous value
            if (!vsync_o) {
                vsync_lines++;
            }
        }
        prev_sof = sof_o;
        
        // --- HSync Pulse Width Measurement ---
        if (!hsync_o) {
            hsync_width++;
        }

        if (hsync_o && !prev_hsync) {
            printf("HSync pulse: %lu px\n", hsync_width);
            hsync_width = 0;
        }

        prev_hsync = hsync_o;
        // --- VSync Line Count Measurement ---
        if (vsync_o && !prev_vsync) {
            printf("VSync lines: %lu\n", vsync_lines);
            vsync_lines = 0;
        }
        prev_vsync = vsync_o;
        
        // --- Frame Cycle Counter ---
        frame_cycles++;
        
        // --- Falling Clock Edge ---
        clk_pix_i = 0;
        tb->clk_pix_i = clk_pix_i;
        tb->eval();
    }
    
    // === PHASE 5: Final Assertions ===
    fclose(ppm_fp);
    printf("Total DE cycles: %lu (expected 614400)\n", de_count);
    if (de_count == 614400) {
        printf("DE count: PASS\n");
    } else {
        printf("DE count: FAIL\n");
    }
    delete tb;
    
    return 0;
}